---
title: "Sprievodca Ekonometriou"
output: 
  pdf_document:
    keep_tex: yes
  html_document:
    df_print: paged
    keep_md: true
---

# Úvod

## Sprievodca ekfmetriou

Sprievodca ekonometriou má za úlohu priblížiť Vám ekonometriu, a pomôcť Vám jej porozumieť. Sprievodcu píšem ako študent, ktorý sa ekonometriu začal učiť sám, a sám si prešiel zdĺhavým procesom bádania a usmerňovania. Sprievodca je zostrojený ako-tak súbežne s osnovou a zadaniami, ktoré obdržíte na hodine. Nebudeme sa konkrétne držať vypracovania zadaní, ale skôr princípmi, z ktorých zadania ťažia. Mnoho študentov tento predmet nezaujíma, a zadania vypracujú okopírovaním postupov starších spolužiakov, nuž, pochopiť ekonometriu a jej postupy nie je vôbec jednoduché, a dokážem pochopiť, keď si študenti hľadajú skratky. Na druhú stranu, ekonometria predstavuje skvelú vstupnú bránu do sveta analytiky. Človek je zavalený Machine Learningom, Data Sciencom a AI-čkom, nuž až po sfúknutí pozlátka zistí, že je to zmes matematiky, štatistiky a počítačovej vedy (CS – computer science). Ekonometria je teda skvelou výhovorkou, ako oprášiť matematiku, doučiť sa štatistiku, a naučiť sa troška programovania. R-ko sa môže zdať ako jazyk, ktorý žije v tieni Pythonu, avšak, akoby nejedna Dominika vedela povedať, netreba sa nechať voviesť do omylu. R-ko je najvhodnejší programovací jazyk pre štatistikov, Google ho zahrnul do najnovších kurzov Google Analytics. Mojou úlohou je pomôcť Vám prekonať problém, ktorý som na začiatku svojej cesty ekonometriou vôbec nepovažoval za problém, a to množstvo materiálov, ktoré zavalí študenta. Pomôžem Vám postupne zložiť skladačku konceptov a teórií, na ktorých ekonometria stojí. Náročnosť prezentovania konceptov bude prispôsobená. Nemá zmysel vysvetľovať odvodzovanie každého estimátora. Cieľom je poskytnúť všeobecný náhľad ekonometrie, a pomôcť Vám pochopiť, a teda príjemnejšie zvládnuť predmet Ekonometria.    

&nbsp;  
 
__Čo nás čaká:__  

* Základy programovania v R  
* Intuitívny prehľad štatistických konceptov  
* Ekonometrické techniky 

\newpage

# Základy práce v R  

> Sprievodca je interaktívny, teda začneme stiahnutím a inštaláciou [R](https://cran.r-project.org/mirrors.html) a [RStudia](https://cran.r-project.org/mirrors.html). R má samo o sebe programovacie prostredie, avšak dnešným štandardom je používanie intregrovaného vývojového prostredia (IDE) v podobe RStudia.  



Priradiť hodnotu

## Import údajov
Table Header  
___________
Table cell


no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text no pisem tu novy text 


__test__
# Toto je testik hehehe
**toot vraj spravi bold**

Skusme drbnut aj obrazok

no pisem tu novy text


__test__
# Toto je testik hehehe
**toot vraj spravi bold**

Skusme drbnut aj obrazok

no pisem tu novy text


__test__
# Toto je testik hehehe
**toot vraj spravi bold**

Skusme drbnut aj obrazok

no pisem tu novy text


__test__
# Toto je testik hehehe
**toot vraj spravi bold**

Skusme drbnut aj obrazok

no pisem tu novy text


__test__